easy_admin:
    design:
        assets:
            js:
                - 'bundles/artgrispage/js/jquery.collection.js'
            css:
                - 'bundles/artgrispage/style.css'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@ArtgrisPage/themes/form.html.twig'
    entities:
        ArtgrisPage:
            class: Artgris\Bundle\PageBundle\Entity\ArtgrisPage
            controller: Artgris\Bundle\PageBundle\Controller\PageController
            disabled_actions: ['show']
            templates:
                edit: "@ArtgrisPage/edit.html.twig"
                new: "@ArtgrisPage/new.html.twig"
            list:
                title: artgrispage.list.title
                actions:
                    - { name: 'editBlocks', icon: 'pencil', label: false }
                    - { name: 'edit', icon: 'cog', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
                    - { name: 'new',  label: 'artgrispage.action.new' }
                fields:
                    - { property: 'name' , label: form.name.label }
                    - { property: 'route', label: form.route.label, template: '@ArtgrisPage/fields/field_route.html.twig' }
                    - { property: 'blocks' , label: form.blocks.label }
            edit:
                title: 'artgrispage.action.edit'
            form:
                title: artgrispage.action.new
                fields:
                    - name
                    - { property: 'slug', label: "form.slug.placeholder",  help: 'form.slug.help', type_options: { required: false } }